title: VPN for VRChat
tagline: Как заходить в VRChat в эпоху ограниченного интернета
description: Как заходить в VRChat в эпоху ограниченного интернета
url: https://kawashirov.github.io/vpn-for-vrchat/
logo: ./opengraph-image-480x270.png
image: ./opengraph-image-480x270.png
author: kawashirov
email: 1196609+kawashirov@users.noreply.github.com

title-on-all-pages: false
color-mode: "dark"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  # turn off smart quotes: https://stackoverflow.com/a/25597026/5698182
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - jekyll-seo-tag
  - jemoji
