author: kawashirov
email: 1196609+kawashirov@users.noreply.github.com

color-mode: "dark"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  # turn off smart quotes: https://stackoverflow.com/a/25597026/5698182
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - jemoji
